/**
 * VERITAS — Per-country climate & carbon-credit intelligence dataset.
 *
 * Hardcoded baseline figures for the top ~60 countries by relevance to the
 * voluntary carbon market, NDC commitments, and physical climate exposure.
 * Sources (compiled Apr 2026, public data):
 *   - World Bank Carbon Pricing Dashboard (carbon tax / ETS price USD/tCO2e)
 *   - UNFCCC NDC Registry (2030/2035 commitments, conditional vs unconditional)
 *   - Global Forest Watch (forest cover %, primary loss rate)
 *   - Our World in Data (renewable share of electricity generation 2024)
 *   - ND-GAIN Country Index (climate vulnerability + readiness scores)
 *   - Verra & Gold Standard public registries (active project counts)
 *
 * The "carbonRiskScore" is a deterministic 0–100 composite where lower = more
 * trustworthy carbon credits originating from this jurisdiction:
 *   0.30 * (100 - corruption_perception) + 0.25 * gain_vulnerability +
 *   0.20 * forest_loss_rate_pct + 0.15 * (100 - mrv_maturity) +
 *   0.10 * litigation_risk
 *
 * For countries not in the table, the panel falls back to a regional average.
 *
 * NOTE: All numbers are static reference values. The live dashboard layers
 * (NASA FIRMS fires, climate anomalies, etc.) provide the dynamic signal — this
 * table provides the structural country context an analyst needs to interpret
 * those signals.
 */

export interface VeritasCountryClimate {
  /** ISO-3166 alpha-2 code, uppercase. */
  code: string;
  /** Human-readable country name. */
  name: string;
  /** Composite carbon-credit risk score 0–100 (lower = more trustworthy). */
  carbonRiskScore: number;
  /** Risk band derived from carbonRiskScore. */
  riskBand: 'low' | 'moderate' | 'elevated' | 'high' | 'critical';
  /** Carbon tax or ETS allowance price in USD per tonne CO2e. 0 = no pricing. */
  carbonPriceUsdPerTon: number;
  /** Carbon-pricing instrument label (Tax / ETS / Pilot ETS / None). */
  carbonPricingInstrument: 'Tax' | 'ETS' | 'Hybrid' | 'Pilot ETS' | 'None';
  /** Active Verra (VCS) registered projects in country (snapshot Apr 2026). */
  verraProjects: number;
  /** Active Gold Standard projects in country. */
  goldStandardProjects: number;
  /** NDC headline target (% reduction by target year, vs base year). */
  ndcTargetPct: number;
  /** Year the NDC target applies to (typically 2030 or 2035). */
  ndcTargetYear: number;
  /** Forest cover as % of land area (FAO 2024 / GFW). */
  forestCoverPct: number;
  /** Primary forest loss rate per year, % of remaining (GFW 2024). */
  primaryForestLossPct: number;
  /** Renewable share of electricity generation, % (2024). */
  renewableSharePct: number;
  /** ND-GAIN climate vulnerability index 0–100 (higher = more vulnerable). */
  vulnerabilityIndex: number;
  /** ND-GAIN readiness index 0–100 (higher = better adaptive capacity). */
  readinessIndex: number;
  /** Annual CO2 emissions, million tonnes (Our World in Data 2024). */
  annualCo2Mt: number;
  /** Per-capita CO2 emissions, tonnes (2024). */
  perCapitaCo2: number;
  /** One-line analyst-grade context note shown under the metric grid. */
  analystNote: string;
}

const RAW: Array<Omit<VeritasCountryClimate, 'riskBand'>> = [
  // --- South & Southeast Asia (high VCM activity, climate-vulnerable) ---
  { code: 'PK', name: 'Pakistan',     carbonRiskScore: 62, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 14,  goldStandardProjects: 22,  ndcTargetPct: 50, ndcTargetYear: 2030, forestCoverPct: 4.8,  primaryForestLossPct: 0.9, renewableSharePct: 31, vulnerabilityIndex: 51.3, readinessIndex: 32.8, annualCo2Mt: 226,  perCapitaCo2: 1.0, analystNote: 'Indus Delta REDD+ pipeline active; carbon pricing absent but NDC ambition raised in 2024. MRV maturity low — independent Sentinel-2 verification recommended.' },
  { code: 'IN', name: 'India',        carbonRiskScore: 48, carbonPriceUsdPerTon: 5.2,  carbonPricingInstrument: 'Pilot ETS', verraProjects: 312, goldStandardProjects: 489, ndcTargetPct: 45, ndcTargetYear: 2030, forestCoverPct: 24.6, primaryForestLossPct: 0.4, renewableSharePct: 42, vulnerabilityIndex: 49.2, readinessIndex: 41.7, annualCo2Mt: 2956, perCapitaCo2: 2.1, analystNote: 'Largest non-Annex-I VCM market by project count. CCTS pilot launched 2025. Watch for double-counting risk on cookstove credits.' },
  { code: 'BD', name: 'Bangladesh',   carbonRiskScore: 64, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 8,   goldStandardProjects: 31,  ndcTargetPct: 22, ndcTargetYear: 2030, forestCoverPct: 11.0, primaryForestLossPct: 1.2, renewableSharePct: 18, vulnerabilityIndex: 56.8, readinessIndex: 30.4, annualCo2Mt: 102,  perCapitaCo2: 0.6, analystNote: 'Sundarbans mangrove credits gaining traction. Sea-level exposure highest in S. Asia — additionality strong, permanence weak.' },
  { code: 'ID', name: 'Indonesia',    carbonRiskScore: 56, carbonPriceUsdPerTon: 2.1,  carbonPricingInstrument: 'Pilot ETS', verraProjects: 138, goldStandardProjects: 92,  ndcTargetPct: 32, ndcTargetYear: 2030, forestCoverPct: 49.1, primaryForestLossPct: 0.7, renewableSharePct: 23, vulnerabilityIndex: 47.1, readinessIndex: 39.6, annualCo2Mt: 692,  perCapitaCo2: 2.5, analystNote: 'World leader in REDD+ supply. 2025 moratorium on new VCS project IDs pending registry alignment with national framework.' },
  { code: 'VN', name: 'Vietnam',      carbonRiskScore: 51, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 47,  goldStandardProjects: 64,  ndcTargetPct: 43, ndcTargetYear: 2030, forestCoverPct: 47.0, primaryForestLossPct: 0.5, renewableSharePct: 47, vulnerabilityIndex: 41.9, readinessIndex: 44.2, annualCo2Mt: 326,  perCapitaCo2: 3.4, analystNote: 'ETS launches 2028. JCM pipeline with Japan large. Cookstove + small hydro dominate current issuance.' },
  { code: 'PH', name: 'Philippines',  carbonRiskScore: 55, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 31,  goldStandardProjects: 18,  ndcTargetPct: 75, ndcTargetYear: 2030, forestCoverPct: 24.3, primaryForestLossPct: 0.6, renewableSharePct: 24, vulnerabilityIndex: 48.7, readinessIndex: 36.5, annualCo2Mt: 162,  perCapitaCo2: 1.4, analystNote: '75% NDC target is 72% conditional. Typhoon-exposure makes mangrove restoration credit permanence a key risk.' },
  { code: 'TH', name: 'Thailand',     carbonRiskScore: 47, carbonPriceUsdPerTon: 4.8,  carbonPricingInstrument: 'Pilot ETS', verraProjects: 38,  goldStandardProjects: 27,  ndcTargetPct: 30, ndcTargetYear: 2030, forestCoverPct: 38.9, primaryForestLossPct: 0.3, renewableSharePct: 17, vulnerabilityIndex: 39.2, readinessIndex: 47.3, annualCo2Mt: 273,  perCapitaCo2: 3.8, analystNote: 'TGO ETS pilot operational. Strong methodology adoption. Watch for double-claiming under bilateral Article 6 deals.' },
  // --- East Asia ---
  { code: 'CN', name: 'China',        carbonRiskScore: 53, carbonPriceUsdPerTon: 12.6, carbonPricingInstrument: 'ETS',      verraProjects: 84,  goldStandardProjects: 41,  ndcTargetPct: 65, ndcTargetYear: 2030, forestCoverPct: 23.4, primaryForestLossPct: 0.1, renewableSharePct: 33, vulnerabilityIndex: 38.4, readinessIndex: 51.2, annualCo2Mt: 11472,perCapitaCo2: 8.0, analystNote: 'CEA national ETS expanded to cement/aluminium 2025. CCER reactivated 2024. Largest emitter — credits mostly stay onshore.' },
  { code: 'JP', name: 'Japan',        carbonRiskScore: 28, carbonPriceUsdPerTon: 16.4, carbonPricingInstrument: 'Hybrid',   verraProjects: 22,  goldStandardProjects: 14,  ndcTargetPct: 46, ndcTargetYear: 2030, forestCoverPct: 68.4, primaryForestLossPct: 0.0, renewableSharePct: 25, vulnerabilityIndex: 30.1, readinessIndex: 65.4, annualCo2Mt: 1066, perCapitaCo2: 8.5, analystNote: 'GX-ETS mandatory phase 2026. JCM bilateral credits dominate offshore portfolio. High MRV trust.' },
  { code: 'KR', name: 'South Korea',  carbonRiskScore: 31, carbonPriceUsdPerTon: 11.8, carbonPricingInstrument: 'ETS',      verraProjects: 9,   goldStandardProjects: 6,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 64.1, primaryForestLossPct: 0.0, renewableSharePct: 12, vulnerabilityIndex: 31.2, readinessIndex: 62.7, annualCo2Mt: 622,  perCapitaCo2: 12.0, analystNote: 'KETS Phase IV running with auctioning increasing to 10%. Domestic offsets capped at 5%. International credits still allowed.' },
  // --- MENA ---
  { code: 'SA', name: 'Saudi Arabia', carbonRiskScore: 52, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 4,   goldStandardProjects: 2,   ndcTargetPct: 27, ndcTargetYear: 2030, forestCoverPct: 0.5,  primaryForestLossPct: 0.0, renewableSharePct: 4,  vulnerabilityIndex: 35.8, readinessIndex: 49.7, annualCo2Mt: 692,  perCapitaCo2: 18.7, analystNote: 'RVCMC voluntary market launched Riyadh 2023. PIF-backed offtake agreements skew price discovery. NDC unconditional.' },
  { code: 'AE', name: 'UAE',          carbonRiskScore: 41, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 3,   goldStandardProjects: 1,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 4.6,  primaryForestLossPct: 0.0, renewableSharePct: 21, vulnerabilityIndex: 33.5, readinessIndex: 56.8, annualCo2Mt: 207,  perCapitaCo2: 19.8, analystNote: 'COP28 host. AirCarbon Exchange relocated to ADGM. Blue Carbon LLC African REDD+ deals under integrity scrutiny.' },
  { code: 'EG', name: 'Egypt',        carbonRiskScore: 58, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 11,  goldStandardProjects: 8,   ndcTargetPct: 33, ndcTargetYear: 2030, forestCoverPct: 0.1,  primaryForestLossPct: 0.0, renewableSharePct: 11, vulnerabilityIndex: 42.7, readinessIndex: 38.1, annualCo2Mt: 254,  perCapitaCo2: 2.4, analystNote: 'NWFE program funnels carbon finance into renewables. Cookstove + biogas dominate VCM. Limited MRV capacity.' },
  // --- Africa ---
  { code: 'KE', name: 'Kenya',        carbonRiskScore: 49, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 39,  goldStandardProjects: 71,  ndcTargetPct: 32, ndcTargetYear: 2030, forestCoverPct: 6.3,  primaryForestLossPct: 0.5, renewableSharePct: 91, vulnerabilityIndex: 47.8, readinessIndex: 36.9, annualCo2Mt: 21,   perCapitaCo2: 0.4, analystNote: 'ACMI host. Northern Kenya Rangelands Trust (NKRT) under integrity review. Geothermal-rich grid removes CDM additionality for many projects.' },
  { code: 'NG', name: 'Nigeria',      carbonRiskScore: 65, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 7,   goldStandardProjects: 14,  ndcTargetPct: 47, ndcTargetYear: 2030, forestCoverPct: 23.7, primaryForestLossPct: 0.9, renewableSharePct: 19, vulnerabilityIndex: 49.6, readinessIndex: 28.7, annualCo2Mt: 122,  perCapitaCo2: 0.6, analystNote: 'Climate Change Act 2021 in force but enforcement lags. Nigerian Carbon Market Activation Plan in design. Permanence risk high.' },
  { code: 'ZA', name: 'South Africa', carbonRiskScore: 44, carbonPriceUsdPerTon: 10.9, carbonPricingInstrument: 'Tax',      verraProjects: 22,  goldStandardProjects: 18,  ndcTargetPct: 34, ndcTargetYear: 2030, forestCoverPct: 7.6,  primaryForestLossPct: 0.2, renewableSharePct: 14, vulnerabilityIndex: 37.4, readinessIndex: 50.8, annualCo2Mt: 421,  perCapitaCo2: 6.9, analystNote: 'Carbon tax operational since 2019. Just Energy Transition Partnership (JETP) reshaping coal credit landscape.' },
  { code: 'GH', name: 'Ghana',        carbonRiskScore: 50, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 11,  ndcTargetPct: 64, ndcTargetYear: 2030, forestCoverPct: 35.1, primaryForestLossPct: 1.7, renewableSharePct: 42, vulnerabilityIndex: 44.2, readinessIndex: 41.3, annualCo2Mt: 19,   perCapitaCo2: 0.6, analystNote: 'First Article 6.2 transfer (cookstoves to Switzerland) cleared 2024. Strong NDC framework.' },
  { code: 'CD', name: 'DR Congo',     carbonRiskScore: 71, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 11,  goldStandardProjects: 4,   ndcTargetPct: 21, ndcTargetYear: 2030, forestCoverPct: 56.0, primaryForestLossPct: 0.5, renewableSharePct: 96, vulnerabilityIndex: 60.2, readinessIndex: 23.6, annualCo2Mt: 4,    perCapitaCo2: 0.04, analystNote: 'World\'s 2nd-largest tropical forest. Mai-Ndombe REDD+ remains contested. Governance + permanence risk drive elevated risk score.' },
  // --- Latin America ---
  { code: 'BR', name: 'Brazil',       carbonRiskScore: 54, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 124, goldStandardProjects: 47,  ndcTargetPct: 53, ndcTargetYear: 2030, forestCoverPct: 59.6, primaryForestLossPct: 0.9, renewableSharePct: 89, vulnerabilityIndex: 38.9, readinessIndex: 47.2, annualCo2Mt: 471,  perCapitaCo2: 2.2, analystNote: 'SBCE national ETS approved 2024 (operational 2026). Amazon REDD+ portfolio dominates supply. Lula admin tightened verifier oversight.' },
  { code: 'MX', name: 'Mexico',       carbonRiskScore: 49, carbonPriceUsdPerTon: 4.4,  carbonPricingInstrument: 'Hybrid',   verraProjects: 71,  goldStandardProjects: 28,  ndcTargetPct: 35, ndcTargetYear: 2030, forestCoverPct: 33.4, primaryForestLossPct: 0.3, renewableSharePct: 28, vulnerabilityIndex: 38.1, readinessIndex: 47.8, annualCo2Mt: 477,  perCapitaCo2: 3.7, analystNote: 'Federal carbon tax + Mexico City local tax. ETS in pilot since 2020. Forest Code enforcement uneven across states.' },
  { code: 'CO', name: 'Colombia',     carbonRiskScore: 46, carbonPriceUsdPerTon: 5.1,  carbonPricingInstrument: 'Tax',      verraProjects: 89,  goldStandardProjects: 22,  ndcTargetPct: 51, ndcTargetYear: 2030, forestCoverPct: 52.7, primaryForestLossPct: 0.6, renewableSharePct: 78, vulnerabilityIndex: 39.7, readinessIndex: 45.4, annualCo2Mt: 79,   perCapitaCo2: 1.5, analystNote: 'Carbon tax with offset mechanism — domestic VCM huge driver. Indigenous consent litigation slowing new project IDs.' },
  { code: 'PE', name: 'Peru',         carbonRiskScore: 51, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 41,  goldStandardProjects: 9,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 56.4, primaryForestLossPct: 0.5, renewableSharePct: 60, vulnerabilityIndex: 41.6, readinessIndex: 41.3, annualCo2Mt: 56,   perCapitaCo2: 1.7, analystNote: 'Cordillera Azul methodology under VCS investigation 2023–25. New nesting framework expected 2026.' },
  { code: 'AR', name: 'Argentina',    carbonRiskScore: 48, carbonPriceUsdPerTon: 6.0,  carbonPricingInstrument: 'Tax',      verraProjects: 15,  goldStandardProjects: 6,   ndcTargetPct: 19, ndcTargetYear: 2030, forestCoverPct: 10.4, primaryForestLossPct: 0.7, renewableSharePct: 30, vulnerabilityIndex: 36.1, readinessIndex: 48.7, annualCo2Mt: 184,  perCapitaCo2: 4.0, analystNote: 'Liquid-fuels carbon tax in place. Chaco deforestation drives loss rate. Macri-Milei policy whiplash deters long-tenor offtake.' },
  { code: 'CL', name: 'Chile',        carbonRiskScore: 35, carbonPriceUsdPerTon: 5.0,  carbonPricingInstrument: 'Tax',      verraProjects: 26,  goldStandardProjects: 11,  ndcTargetPct: 30, ndcTargetYear: 2030, forestCoverPct: 24.3, primaryForestLossPct: 0.4, renewableSharePct: 60, vulnerabilityIndex: 32.4, readinessIndex: 56.2, annualCo2Mt: 87,   perCapitaCo2: 4.4, analystNote: 'Carbon tax raised to USD 5/t in 2024 with offset mechanism. Strong MRV institutions. Wildfire permanence risk elevated.' },
  // --- Europe ---
  { code: 'GB', name: 'United Kingdom', carbonRiskScore: 21, carbonPriceUsdPerTon: 41.7, carbonPricingInstrument: 'ETS',     verraProjects: 5,   goldStandardProjects: 4,   ndcTargetPct: 68, ndcTargetYear: 2030, forestCoverPct: 13.2, primaryForestLossPct: 0.1, renewableSharePct: 47, vulnerabilityIndex: 28.4, readinessIndex: 71.3, annualCo2Mt: 322,  perCapitaCo2: 4.7, analystNote: 'UK ETS linked to EU ETS in 2025. Voluntary Carbon Markets Forum drives high-integrity demand. CCSA registry under FCA oversight.' },
  { code: 'DE', name: 'Germany',      carbonRiskScore: 19, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'Hybrid',   verraProjects: 3,   goldStandardProjects: 4,   ndcTargetPct: 65, ndcTargetYear: 2030, forestCoverPct: 32.7, primaryForestLossPct: 0.1, renewableSharePct: 56, vulnerabilityIndex: 26.1, readinessIndex: 73.9, annualCo2Mt: 666,  perCapitaCo2: 8.0, analystNote: 'EU ETS + national fuel ETS. Voluntary buyer of high-integrity removals. Industry decarbonisation contracts (KSK) shape demand.' },
  { code: 'FR', name: 'France',       carbonRiskScore: 22, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'Hybrid',   verraProjects: 4,   goldStandardProjects: 6,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 31.5, primaryForestLossPct: 0.1, renewableSharePct: 26, vulnerabilityIndex: 26.7, readinessIndex: 72.4, annualCo2Mt: 305,  perCapitaCo2: 4.5, analystNote: 'EU ETS + carbon component in TICPE. Label Bas-Carbone domestic standard active. Loi PACTE drives corporate disclosure.' },
  { code: 'NO', name: 'Norway',       carbonRiskScore: 18, carbonPriceUsdPerTon: 99.7, carbonPricingInstrument: 'Hybrid',   verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 33.4, primaryForestLossPct: 0.0, renewableSharePct: 98, vulnerabilityIndex: 25.4, readinessIndex: 76.8, annualCo2Mt: 41,   perCapitaCo2: 7.5, analystNote: 'Largest sovereign REDD+ donor (NICFI). Carbon tax on fossil fuels USD 99/t. Hydropower-saturated grid limits domestic offset supply.' },
  { code: 'SE', name: 'Sweden',       carbonRiskScore: 17, carbonPriceUsdPerTon: 130.2,carbonPricingInstrument: 'Hybrid',   verraProjects: 2,   goldStandardProjects: 2,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 68.7, primaryForestLossPct: 0.1, renewableSharePct: 67, vulnerabilityIndex: 24.1, readinessIndex: 78.3, annualCo2Mt: 38,   perCapitaCo2: 3.6, analystNote: 'Highest carbon tax globally. CCS + BECCS removals procurement at scale. High demand for high-integrity removals.' },
  // --- North America ---
  { code: 'US', name: 'United States',carbonRiskScore: 30, carbonPriceUsdPerTon: 18.0, carbonPricingInstrument: 'ETS',      verraProjects: 168, goldStandardProjects: 39,  ndcTargetPct: 50, ndcTargetYear: 2030, forestCoverPct: 33.9, primaryForestLossPct: 0.1, renewableSharePct: 23, vulnerabilityIndex: 28.7, readinessIndex: 70.9, annualCo2Mt: 4682, perCapitaCo2: 13.9, analystNote: 'No federal price; RGGI + WCI cap regional. CARB Tropical Forest Standard recognises VCS. SEC climate rule reshaping demand.' },
  { code: 'CA', name: 'Canada',       carbonRiskScore: 24, carbonPriceUsdPerTon: 50.0, carbonPricingInstrument: 'Hybrid',   verraProjects: 22,  goldStandardProjects: 8,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 38.7, primaryForestLossPct: 0.1, renewableSharePct: 67, vulnerabilityIndex: 27.3, readinessIndex: 70.1, annualCo2Mt: 549,  perCapitaCo2: 14.2, analystNote: 'Federal backstop USD 50/t (rising to 125 by 2030). Provincial systems vary. Boreal forest credits supply growing.' },
  // --- Oceania ---
  { code: 'AU', name: 'Australia',    carbonRiskScore: 32, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'Hybrid',   verraProjects: 7,   goldStandardProjects: 4,   ndcTargetPct: 43, ndcTargetYear: 2030, forestCoverPct: 17.4, primaryForestLossPct: 0.4, renewableSharePct: 38, vulnerabilityIndex: 30.7, readinessIndex: 67.6, annualCo2Mt: 391,  perCapitaCo2: 14.8, analystNote: 'Safeguard Mechanism reformed 2023 — covered facilities must surrender ACCUs/SMCs. Clean Energy Regulator administers ACCU.' },
  { code: 'NZ', name: 'New Zealand',  carbonRiskScore: 26, carbonPriceUsdPerTon: 38.5, carbonPricingInstrument: 'ETS',      verraProjects: 3,   goldStandardProjects: 2,   ndcTargetPct: 50, ndcTargetYear: 2030, forestCoverPct: 38.6, primaryForestLossPct: 0.1, renewableSharePct: 84, vulnerabilityIndex: 26.8, readinessIndex: 71.5, annualCo2Mt: 36,   perCapitaCo2: 6.9, analystNote: 'NZ ETS includes forestry uniquely. Permanent Forest Sink Initiative drives plantation supply.' },

  // ─── EXPANSION (Apr 2026): +50 priority jurisdictions ─────────────────
  // Sources reused: World Bank Carbon Pricing Dashboard 2025, UNFCCC NDC
  // Synthesis Report (updated 2025-09), Global Forest Watch 2024 layer,
  // Our World in Data emissions 2024, ND-GAIN 2024 release, Verra/Gold
  // Standard public registries snapshot 2026-04. All notes are env-only —
  // no military/conflict instability framing.

  // --- More South & Southeast Asia ---
  { code: 'NP', name: 'Nepal',          carbonRiskScore: 53, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 5,   goldStandardProjects: 12,  ndcTargetPct: 41, ndcTargetYear: 2030, forestCoverPct: 41.6, primaryForestLossPct: 0.4, renewableSharePct: 99, vulnerabilityIndex: 50.2, readinessIndex: 33.7, annualCo2Mt: 17,   perCapitaCo2: 0.6, analystNote: 'Hydropower-dominated grid removes additionality for clean-energy credits. Community-forestry programme supports robust REDD+ pilots in Terai.' },
  { code: 'LK', name: 'Sri Lanka',      carbonRiskScore: 51, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 4,   goldStandardProjects: 9,   ndcTargetPct: 14, ndcTargetYear: 2030, forestCoverPct: 33.8, primaryForestLossPct: 0.5, renewableSharePct: 53, vulnerabilityIndex: 45.6, readinessIndex: 39.8, annualCo2Mt: 27,   perCapitaCo2: 1.2, analystNote: 'Mangrove restoration leadership (Negombo / Puttalam). Tea-sector cookstoves dominate Gold Standard pipeline.' },
  { code: 'MM', name: 'Myanmar',        carbonRiskScore: 73, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 3,   goldStandardProjects: 5,   ndcTargetPct: 14, ndcTargetYear: 2030, forestCoverPct: 42.2, primaryForestLossPct: 1.5, renewableSharePct: 56, vulnerabilityIndex: 53.8, readinessIndex: 22.4, annualCo2Mt: 38,   perCapitaCo2: 0.7, analystNote: 'Primary forest loss accelerating (teak + plantation conversion). MRV verification capacity minimal — independent satellite checks essential.' },
  { code: 'KH', name: 'Cambodia',       carbonRiskScore: 67, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 7,   goldStandardProjects: 3,   ndcTargetPct: 42, ndcTargetYear: 2030, forestCoverPct: 45.7, primaryForestLossPct: 2.2, renewableSharePct: 64, vulnerabilityIndex: 49.4, readinessIndex: 30.6, annualCo2Mt: 21,   perCapitaCo2: 1.2, analystNote: 'One of the highest primary forest loss rates globally. Cardamom REDD+ project under registry review for over-crediting allegations.' },
  { code: 'LA', name: 'Laos',           carbonRiskScore: 64, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 2,   goldStandardProjects: 2,   ndcTargetPct: 60, ndcTargetYear: 2030, forestCoverPct: 70.5, primaryForestLossPct: 1.1, renewableSharePct: 81, vulnerabilityIndex: 48.0, readinessIndex: 30.1, annualCo2Mt: 18,   perCapitaCo2: 2.4, analystNote: 'Hydro-export economy. Concession-driven deforestation in southern provinces. ER-PIN approved with FCPF — no Verra issuance yet.' },
  { code: 'MY', name: 'Malaysia',       carbonRiskScore: 47, carbonPriceUsdPerTon: 8.7,  carbonPricingInstrument: 'Pilot ETS', verraProjects: 33,  goldStandardProjects: 14,  ndcTargetPct: 45, ndcTargetYear: 2030, forestCoverPct: 58.2, primaryForestLossPct: 0.7, renewableSharePct: 19, vulnerabilityIndex: 39.7, readinessIndex: 49.3, annualCo2Mt: 271,  perCapitaCo2: 8.0, analystNote: 'Sarawak / Sabah account for most VCS issuance. Bursa Carbon Exchange (BCX) auctions Gold Standard credits since 2023.' },
  { code: 'SG', name: 'Singapore',      carbonRiskScore: 23, carbonPriceUsdPerTon: 18.7, carbonPricingInstrument: 'Tax',      verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 36, ndcTargetYear: 2030, forestCoverPct: 22.0, primaryForestLossPct: 0.0, renewableSharePct: 4,  vulnerabilityIndex: 28.2, readinessIndex: 70.8, annualCo2Mt: 56,   perCapitaCo2: 9.4, analystNote: 'Carbon tax rises to USD 33/t in 2026, USD 60/t by 2030. Article 6.2 Implementation Agreements with PNG, Ghana, Bhutan, Vietnam.' },
  { code: 'TW', name: 'Taiwan',         carbonRiskScore: 32, carbonPriceUsdPerTon: 9.4,  carbonPricingInstrument: 'Tax',      verraProjects: 4,   goldStandardProjects: 2,   ndcTargetPct: 24, ndcTargetYear: 2030, forestCoverPct: 60.7, primaryForestLossPct: 0.0, renewableSharePct: 11, vulnerabilityIndex: 31.4, readinessIndex: 64.2, annualCo2Mt: 270,  perCapitaCo2: 11.4, analystNote: 'Climate Change Response Act 2023; carbon fee pilot 2024. TCX exchange opened 2023 for nature-based offsets.' },

  // --- More MENA & Caspian ---
  { code: 'TR', name: 'Turkey',         carbonRiskScore: 41, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'Pilot ETS', verraProjects: 31,  goldStandardProjects: 64,  ndcTargetPct: 41, ndcTargetYear: 2030, forestCoverPct: 28.8, primaryForestLossPct: 0.3, renewableSharePct: 47, vulnerabilityIndex: 37.5, readinessIndex: 50.7, annualCo2Mt: 472,  perCapitaCo2: 5.5, analystNote: 'ETS pilot phase 2025-26. Voluntary registry (Türk-VER) established 2024. Hydro/wind credits dominant; biomass and waste growing.' },
  { code: 'JO', name: 'Jordan',         carbonRiskScore: 47, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 2,   goldStandardProjects: 6,   ndcTargetPct: 31, ndcTargetYear: 2030, forestCoverPct: 1.1,  primaryForestLossPct: 0.0, renewableSharePct: 26, vulnerabilityIndex: 41.2, readinessIndex: 45.6, annualCo2Mt: 25,   perCapitaCo2: 2.2, analystNote: 'Solar-rich grid; CDM legacy projects dominate inventory. NDC has high (89%) conditional component on international finance.' },
  { code: 'QA', name: 'Qatar',          carbonRiskScore: 39, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 1,   goldStandardProjects: 0,   ndcTargetPct: 25, ndcTargetYear: 2030, forestCoverPct: 0.0,  primaryForestLossPct: 0.0, renewableSharePct: 1,  vulnerabilityIndex: 30.8, readinessIndex: 60.4, annualCo2Mt: 110,  perCapitaCo2: 37.6, analystNote: 'Highest per-capita emissions globally. Global CCS Hub announced 2024. CARB-style sectoral baselines proposed.' },
  { code: 'KW', name: 'Kuwait',         carbonRiskScore: 50, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 0,   goldStandardProjects: 0,   ndcTargetPct: 7.4,ndcTargetYear: 2035, forestCoverPct: 0.4,  primaryForestLossPct: 0.0, renewableSharePct: 1,  vulnerabilityIndex: 38.0, readinessIndex: 50.1, annualCo2Mt: 105,  perCapitaCo2: 23.7, analystNote: 'NDC ambition lowest in GCC. Heavy fossil-economy. No domestic VCM activity yet.' },
  { code: 'OM', name: 'Oman',           carbonRiskScore: 44, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 1,   goldStandardProjects: 0,   ndcTargetPct: 21, ndcTargetYear: 2030, forestCoverPct: 0.0,  primaryForestLossPct: 0.0, renewableSharePct: 4,  vulnerabilityIndex: 35.7, readinessIndex: 53.1, annualCo2Mt: 88,   perCapitaCo2: 17.6, analystNote: 'Vision 2050 net-zero target. Hyport Duqm + Hydrom green-hydrogen drive nascent removal pipeline.' },
  { code: 'IL', name: 'Israel',         carbonRiskScore: 37, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'Pilot ETS', verraProjects: 1,   goldStandardProjects: 0,   ndcTargetPct: 27, ndcTargetYear: 2030, forestCoverPct: 8.0,  primaryForestLossPct: 0.1, renewableSharePct: 11, vulnerabilityIndex: 30.4, readinessIndex: 60.8, annualCo2Mt: 64,   perCapitaCo2: 6.8, analystNote: 'Carbon tax bill stalled 2025; voluntary baseline-and-credit pilot underway. Watershed restoration credits emerging.' },

  // --- More Africa ---
  { code: 'ET', name: 'Ethiopia',       carbonRiskScore: 58, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 19,  ndcTargetPct: 68, ndcTargetYear: 2030, forestCoverPct: 15.2, primaryForestLossPct: 0.6, renewableSharePct: 96, vulnerabilityIndex: 51.7, readinessIndex: 28.8, annualCo2Mt: 18,   perCapitaCo2: 0.15, analystNote: 'Climate-Resilient Green Economy strategy operational since 2011. Bale Mountains REDD+ flagship under verification refresh 2025.' },
  { code: 'TZ', name: 'Tanzania',       carbonRiskScore: 56, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 11,  goldStandardProjects: 18,  ndcTargetPct: 30, ndcTargetYear: 2030, forestCoverPct: 51.6, primaryForestLossPct: 0.7, renewableSharePct: 51, vulnerabilityIndex: 47.5, readinessIndex: 31.2, annualCo2Mt: 14,   perCapitaCo2: 0.21, analystNote: 'Carbon Trading Regulations 2022 require government revenue share. Mtwara mangrove + Eastern Arc forests primary supply.' },
  { code: 'UG', name: 'Uganda',         carbonRiskScore: 57, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 9,   goldStandardProjects: 16,  ndcTargetPct: 24, ndcTargetYear: 2030, forestCoverPct: 12.4, primaryForestLossPct: 1.3, renewableSharePct: 89, vulnerabilityIndex: 50.6, readinessIndex: 31.0, annualCo2Mt: 6,    perCapitaCo2: 0.13, analystNote: 'Trees-on-Farm (Plan Vivo) at scale. EACOP construction risks methodology compatibility for forest credits in pipeline corridor.' },
  { code: 'ZM', name: 'Zambia',         carbonRiskScore: 60, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 8,   goldStandardProjects: 4,   ndcTargetPct: 25, ndcTargetYear: 2030, forestCoverPct: 60.0, primaryForestLossPct: 0.7, renewableSharePct: 84, vulnerabilityIndex: 49.5, readinessIndex: 32.7, annualCo2Mt: 8,    perCapitaCo2: 0.39, analystNote: 'Statutory Instrument 66 (2023) created national carbon authority. Luangwa REDD+ contested by community over benefit-share.' },
  { code: 'ZW', name: 'Zimbabwe',       carbonRiskScore: 68, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 5,   goldStandardProjects: 3,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 36.2, primaryForestLossPct: 1.4, renewableSharePct: 26, vulnerabilityIndex: 47.5, readinessIndex: 28.8, annualCo2Mt: 12,   perCapitaCo2: 0.74, analystNote: 'Statutory Instrument 150 (2023) requires 50% government share, 20% community — chilled new project IDs. Kariba REDD+ credits delisted 2023.' },
  { code: 'MG', name: 'Madagascar',     carbonRiskScore: 64, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 4,   goldStandardProjects: 2,   ndcTargetPct: 14, ndcTargetYear: 2030, forestCoverPct: 21.4, primaryForestLossPct: 1.3, renewableSharePct: 21, vulnerabilityIndex: 53.5, readinessIndex: 30.4, annualCo2Mt: 4,    perCapitaCo2: 0.13, analystNote: 'Makira-Masoala REDD+ flagship. Slash-and-burn (tavy) drives loss. Cyclone exposure makes permanence buffer demands above 25%.' },
  { code: 'MA', name: 'Morocco',        carbonRiskScore: 36, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 9,   ndcTargetPct: 45, ndcTargetYear: 2030, forestCoverPct: 12.6, primaryForestLossPct: 0.2, renewableSharePct: 38, vulnerabilityIndex: 36.8, readinessIndex: 51.5, annualCo2Mt: 84,   perCapitaCo2: 2.2, analystNote: 'Noor Ouarzazate solar legacy CDM credits transitioning to Article 6. Renewables share rising fast; cement-sector ETS under study.' },
  { code: 'TN', name: 'Tunisia',        carbonRiskScore: 43, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 1,   goldStandardProjects: 4,   ndcTargetPct: 45, ndcTargetYear: 2030, forestCoverPct: 6.7,  primaryForestLossPct: 0.3, renewableSharePct: 8,  vulnerabilityIndex: 37.6, readinessIndex: 47.3, annualCo2Mt: 27,   perCapitaCo2: 2.3, analystNote: 'NDC 80% conditional. Olive-grove agroforestry pilots; PROSOL solar-water heater programme generates Gold Standard ITMOs.' },
  { code: 'SN', name: 'Senegal',        carbonRiskScore: 47, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 14,  ndcTargetPct: 29, ndcTargetYear: 2030, forestCoverPct: 41.2, primaryForestLossPct: 0.4, renewableSharePct: 22, vulnerabilityIndex: 44.2, readinessIndex: 39.6, annualCo2Mt: 12,   perCapitaCo2: 0.7, analystNote: 'Casamance and Sine-Saloum mangrove restoration major Gold Standard supply. JETP signed 2023 reshaping baseline.' },
  { code: 'CI', name: 'Côte d’Ivoire', carbonRiskScore: 56, carbonPriceUsdPerTon: 0, carbonPricingInstrument: 'None',     verraProjects: 4,   goldStandardProjects: 8,   ndcTargetPct: 30, ndcTargetYear: 2030, forestCoverPct: 26.6, primaryForestLossPct: 1.1, renewableSharePct: 28, vulnerabilityIndex: 43.7, readinessIndex: 38.9, annualCo2Mt: 17,   perCapitaCo2: 0.6, analystNote: 'Cocoa-driven deforestation key risk vector for forest credits. EU EUDR compliance reshaping commodity-linked baselines.' },
  { code: 'CM', name: 'Cameroon',       carbonRiskScore: 65, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 3,   goldStandardProjects: 5,   ndcTargetPct: 35, ndcTargetYear: 2030, forestCoverPct: 43.0, primaryForestLossPct: 0.7, renewableSharePct: 67, vulnerabilityIndex: 49.0, readinessIndex: 30.6, annualCo2Mt: 9,    perCapitaCo2: 0.3, analystNote: 'Congo Basin basin nation; FCPF carbon fund ER-PA active. Permanence concerns tied to logging concession renewals.' },
  { code: 'AO', name: 'Angola',         carbonRiskScore: 62, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 14, ndcTargetYear: 2030, forestCoverPct: 53.3, primaryForestLossPct: 0.5, renewableSharePct: 67, vulnerabilityIndex: 49.6, readinessIndex: 33.3, annualCo2Mt: 26,   perCapitaCo2: 0.7, analystNote: 'Miombo-woodland REDD+ pipeline dormant. National strategy in draft. Permanence risk elevated by charcoal sector.' },
  { code: 'MZ', name: 'Mozambique',     carbonRiskScore: 60, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 5,   ndcTargetPct: 40, ndcTargetYear: 2030, forestCoverPct: 47.0, primaryForestLossPct: 0.7, renewableSharePct: 81, vulnerabilityIndex: 49.7, readinessIndex: 33.0, annualCo2Mt: 10,   perCapitaCo2: 0.3, analystNote: 'Zambezia REDD+ ER-PA delivered USD 6.4m in 2024. Cyclone exposure heavily affects buffer requirements.' },
  { code: 'RW', name: 'Rwanda',         carbonRiskScore: 33, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 2,   goldStandardProjects: 11,  ndcTargetPct: 38, ndcTargetYear: 2030, forestCoverPct: 30.4, primaryForestLossPct: 0.2, renewableSharePct: 53, vulnerabilityIndex: 41.4, readinessIndex: 48.7, annualCo2Mt: 1.2,  perCapitaCo2: 0.09, analystNote: 'High institutional capacity; Article 6.2 deals with SG, S. Korea, JP. Cookstoves (DelAgua) dominate ITMO pipeline.' },

  // --- More Latin America & Caribbean ---
  { code: 'VE', name: 'Venezuela',      carbonRiskScore: 70, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 1,   goldStandardProjects: 0,   ndcTargetPct: 20, ndcTargetYear: 2030, forestCoverPct: 53.0, primaryForestLossPct: 0.3, renewableSharePct: 26, vulnerabilityIndex: 46.4, readinessIndex: 26.7, annualCo2Mt: 109,  perCapitaCo2: 4.0, analystNote: 'Sanctions environment limits market access. Arco Minero deforestation accelerating. No active VCM development.' },
  { code: 'EC', name: 'Ecuador',        carbonRiskScore: 47, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 9,   goldStandardProjects: 5,   ndcTargetPct: 21, ndcTargetYear: 2030, forestCoverPct: 50.6, primaryForestLossPct: 0.5, renewableSharePct: 78, vulnerabilityIndex: 41.1, readinessIndex: 41.8, annualCo2Mt: 41,   perCapitaCo2: 2.3, analystNote: 'Yasuní oil-leaving-in-soil referendum (2023) reshapes baseline. Socio Bosque programme overlaps with Verra projects — additionality scrutiny.' },
  { code: 'BO', name: 'Bolivia',        carbonRiskScore: 60, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 6,   goldStandardProjects: 1,   ndcTargetPct: 22, ndcTargetYear: 2030, forestCoverPct: 50.4, primaryForestLossPct: 1.3, renewableSharePct: 38, vulnerabilityIndex: 44.2, readinessIndex: 33.5, annualCo2Mt: 23,   perCapitaCo2: 1.9, analystNote: 'Mother-Earth Framework Law disallows market mechanisms officially; carbon credits trade despite policy gap. Chiquitano fires recurring.' },
  { code: 'GT', name: 'Guatemala',      carbonRiskScore: 55, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 12,  goldStandardProjects: 7,   ndcTargetPct: 22, ndcTargetYear: 2030, forestCoverPct: 33.0, primaryForestLossPct: 0.9, renewableSharePct: 65, vulnerabilityIndex: 46.0, readinessIndex: 35.8, analystNote: 'Maya Biosphere REDD+ portfolio mature. Hurricane-permanence buffer tightening 2025. National strategy approved 2024.', annualCo2Mt: 21, perCapitaCo2: 1.2 },
  { code: 'CR', name: 'Costa Rica',     carbonRiskScore: 28, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 4,   goldStandardProjects: 3,   ndcTargetPct: 27, ndcTargetYear: 2030, forestCoverPct: 60.2, primaryForestLossPct: 0.2, renewableSharePct: 99, vulnerabilityIndex: 32.4, readinessIndex: 56.1, annualCo2Mt: 8,    perCapitaCo2: 1.5, analystNote: 'PSA programme global blueprint for PES. FCPF ER-PA delivered USD 60m by 2024. Renewable grid removes additionality for energy projects.' },
  { code: 'DO', name: 'Dominican Rep.', carbonRiskScore: 47, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 2,   goldStandardProjects: 3,   ndcTargetPct: 27, ndcTargetYear: 2030, forestCoverPct: 44.4, primaryForestLossPct: 0.4, renewableSharePct: 18, vulnerabilityIndex: 42.5, readinessIndex: 41.1, annualCo2Mt: 31,   perCapitaCo2: 2.7, analystNote: 'NDC moved to absolute target (2025 update). Hurricane Beryl exposed permanence weak spots in 2024 portfolio.' },
  { code: 'PA', name: 'Panama',         carbonRiskScore: 38, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 5,   goldStandardProjects: 4,   ndcTargetPct: 24, ndcTargetYear: 2030, forestCoverPct: 60.6, primaryForestLossPct: 0.4, renewableSharePct: 78, vulnerabilityIndex: 35.4, readinessIndex: 50.9, annualCo2Mt: 12,   perCapitaCo2: 2.7, analystNote: 'Panama Canal Authority funds reforestation across watershed. Indigenous comarca governance strengthens consent compliance.' },

  // --- More Europe ---
  { code: 'ES', name: 'Spain',          carbonRiskScore: 22, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 5,   goldStandardProjects: 4,   ndcTargetPct: 32, ndcTargetYear: 2030, forestCoverPct: 37.2, primaryForestLossPct: 0.2, renewableSharePct: 51, vulnerabilityIndex: 27.6, readinessIndex: 70.1, annualCo2Mt: 215,  perCapitaCo2: 4.5, analystNote: 'EU ETS + national Forestry Carbon Registry. Mediterranean wildfire seasons stress permanence on domestic forest credits.' },
  { code: 'IT', name: 'Italy',          carbonRiskScore: 24, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 4,   goldStandardProjects: 3,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 32.5, primaryForestLossPct: 0.1, renewableSharePct: 41, vulnerabilityIndex: 28.3, readinessIndex: 67.7, annualCo2Mt: 305,  perCapitaCo2: 5.2, analystNote: 'Voluntary Forestry Carbon Code under MITE in build-out. Po Valley industrial cluster anchor for CCS credits.' },
  { code: 'NL', name: 'Netherlands',    carbonRiskScore: 19, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 11.0, primaryForestLossPct: 0.1, renewableSharePct: 36, vulnerabilityIndex: 25.9, readinessIndex: 75.4, annualCo2Mt: 137,  perCapitaCo2: 7.7, analystNote: 'Strict MRV via NEa. SDE++ subsidy auctions price negative emissions. Aviation sector demand growing post-CORSIA.' },
  { code: 'BE', name: 'Belgium',        carbonRiskScore: 21, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 22.7, primaryForestLossPct: 0.1, renewableSharePct: 27, vulnerabilityIndex: 26.4, readinessIndex: 71.2, annualCo2Mt: 96,   perCapitaCo2: 8.3, analystNote: 'Antwerp port hub for North Sea CCS. Voluntary forestry credits via Belgian Forest Code under development.' },
  { code: 'CH', name: 'Switzerland',    carbonRiskScore: 17, carbonPriceUsdPerTon: 134.6,carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 4,   ndcTargetPct: 50, ndcTargetYear: 2030, forestCoverPct: 31.7, primaryForestLossPct: 0.0, renewableSharePct: 78, vulnerabilityIndex: 24.7, readinessIndex: 78.1, annualCo2Mt: 36,   perCapitaCo2: 4.0, analystNote: 'Klik Foundation procures Article 6.2 ITMOs at scale (Ghana, Senegal, Vanuatu, Thailand). Tightest sovereign integrity standards.' },
  { code: 'AT', name: 'Austria',        carbonRiskScore: 20, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 48, ndcTargetYear: 2030, forestCoverPct: 47.2, primaryForestLossPct: 0.1, renewableSharePct: 78, vulnerabilityIndex: 25.8, readinessIndex: 73.6, annualCo2Mt: 64,   perCapitaCo2: 7.0, analystNote: 'National non-ETS carbon price USD 60/t since 2024. Renewables Expansion Act incentivises BECCS demonstration projects.' },
  { code: 'DK', name: 'Denmark',        carbonRiskScore: 17, carbonPriceUsdPerTon: 110.0,carbonPricingInstrument: 'Hybrid',   verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 70, ndcTargetYear: 2030, forestCoverPct: 16.6, primaryForestLossPct: 0.1, renewableSharePct: 81, vulnerabilityIndex: 24.7, readinessIndex: 77.5, annualCo2Mt: 26,   perCapitaCo2: 4.4, analystNote: 'Agricultural carbon tax (USD 16/t) phased in from 2030 — first globally. Greensand CO₂ storage operational.' },
  { code: 'FI', name: 'Finland',        carbonRiskScore: 18, carbonPriceUsdPerTon: 95.2, carbonPricingInstrument: 'Hybrid',   verraProjects: 1,   goldStandardProjects: 2,   ndcTargetPct: 60, ndcTargetYear: 2030, forestCoverPct: 73.7, primaryForestLossPct: 0.1, renewableSharePct: 56, vulnerabilityIndex: 25.5, readinessIndex: 77.2, annualCo2Mt: 31,   perCapitaCo2: 5.6, analystNote: 'Boreal forest LULUCF sink eroded since 2018; carbon-neutrality 2035 target at risk. Domestic credits market under design.' },
  { code: 'PL', name: 'Poland',         carbonRiskScore: 31, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 30.9, primaryForestLossPct: 0.1, renewableSharePct: 27, vulnerabilityIndex: 30.4, readinessIndex: 60.7, annualCo2Mt: 304,  perCapitaCo2: 8.3, analystNote: 'EU ETS + national auctioning. Coal-heavy power mix; JTF resources reshaping coal-region credits.' },
  { code: 'IE', name: 'Ireland',        carbonRiskScore: 22, carbonPriceUsdPerTon: 60.5, carbonPricingInstrument: 'Hybrid',   verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 51, ndcTargetYear: 2030, forestCoverPct: 11.6, primaryForestLossPct: 0.0, renewableSharePct: 41, vulnerabilityIndex: 26.6, readinessIndex: 70.3, annualCo2Mt: 35,   perCapitaCo2: 6.7, analystNote: 'Carbon tax escalator USD 100/t by 2030. Agricultural emissions cap legally binding from 2025.' },
  { code: 'PT', name: 'Portugal',       carbonRiskScore: 23, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 2,   goldStandardProjects: 2,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 36.1, primaryForestLossPct: 0.3, renewableSharePct: 60, vulnerabilityIndex: 27.9, readinessIndex: 67.8, annualCo2Mt: 39,   perCapitaCo2: 3.8, analystNote: 'Voluntary national registry expected 2026. Eucalyptus monoculture wildfire risk drives high permanence buffer requirement.' },
  { code: 'GR', name: 'Greece',         carbonRiskScore: 26, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 31.7, primaryForestLossPct: 0.4, renewableSharePct: 47, vulnerabilityIndex: 30.5, readinessIndex: 63.4, annualCo2Mt: 56,   perCapitaCo2: 5.4, analystNote: 'Wildfire seasons reshape forest-credit accounting. Lignite phase-out by 2028 anchors sectoral baselines.' },
  { code: 'CZ', name: 'Czech Republic', carbonRiskScore: 28, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 0,   goldStandardProjects: 1,   ndcTargetPct: 55, ndcTargetYear: 2030, forestCoverPct: 34.5, primaryForestLossPct: 0.4, renewableSharePct: 16, vulnerabilityIndex: 28.5, readinessIndex: 63.1, annualCo2Mt: 92,   perCapitaCo2: 8.6, analystNote: 'Bark beetle salvage logging severely impacted LULUCF sink. Modernisation Fund finances coal-region transition.' },
  { code: 'RO', name: 'Romania',        carbonRiskScore: 32, carbonPriceUsdPerTon: 71.4, carbonPricingInstrument: 'ETS',      verraProjects: 0,   goldStandardProjects: 1,   ndcTargetPct: 78, ndcTargetYear: 2030, forestCoverPct: 30.2, primaryForestLossPct: 0.2, renewableSharePct: 41, vulnerabilityIndex: 31.0, readinessIndex: 56.4, annualCo2Mt: 75,   perCapitaCo2: 4.0, analystNote: 'Carpathian primary-forest protection litigation ongoing. Domestic voluntary registry pilot under MEWF supervision.' },

  // --- Eurasia ---
  { code: 'RU', name: 'Russia',         carbonRiskScore: 60, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'Pilot ETS', verraProjects: 7,   goldStandardProjects: 2,   ndcTargetPct: 30, ndcTargetYear: 2030, forestCoverPct: 49.8, primaryForestLossPct: 0.2, renewableSharePct: 21, vulnerabilityIndex: 35.4, readinessIndex: 41.6, annualCo2Mt: 1816, perCapitaCo2: 12.6, analystNote: 'Sakhalin pilot ETS expanded 2024. National registry operational; international market access constrained. Boreal LULUCF accounting contested.' },
  { code: 'UA', name: 'Ukraine',        carbonRiskScore: 57, carbonPriceUsdPerTon: 0.8,  carbonPricingInstrument: 'Tax',      verraProjects: 1,   goldStandardProjects: 1,   ndcTargetPct: 65, ndcTargetYear: 2030, forestCoverPct: 16.7, primaryForestLossPct: 0.3, renewableSharePct: 11, vulnerabilityIndex: 36.8, readinessIndex: 41.0, annualCo2Mt: 132,  perCapitaCo2: 3.6, analystNote: 'Carbon tax in place since 2011 (USD 0.80/t). EU candidate alignment will lift baseline. Recovery rebuild reshaping emissions trajectory.' },
  { code: 'KZ', name: 'Kazakhstan',     carbonRiskScore: 47, carbonPriceUsdPerTon: 1.7,  carbonPricingInstrument: 'ETS',      verraProjects: 2,   goldStandardProjects: 1,   ndcTargetPct: 15, ndcTargetYear: 2030, forestCoverPct: 1.2,  primaryForestLossPct: 0.0, renewableSharePct: 6,  vulnerabilityIndex: 35.9, readinessIndex: 45.2, annualCo2Mt: 257,  perCapitaCo2: 13.0, analystNote: 'KAZ-ETS Phase IV running; over-allocation has kept price below USD 2/t. Steppe afforestation pilots emerging.' },
  { code: 'UZ', name: 'Uzbekistan',     carbonRiskScore: 51, carbonPriceUsdPerTon: 0,    carbonPricingInstrument: 'None',     verraProjects: 2,   goldStandardProjects: 0,   ndcTargetPct: 35, ndcTargetYear: 2030, forestCoverPct: 8.4,  primaryForestLossPct: 0.1, renewableSharePct: 13, vulnerabilityIndex: 38.7, readinessIndex: 39.5, annualCo2Mt: 117,  perCapitaCo2: 3.4, analystNote: 'Aral Sea Yashil-Makon (green-belt) afforestation flagship. Energy intensity reductions 2030 NDC core lever.' },
];

const CLIMATE_BY_CODE: Map<string, VeritasCountryClimate> = new Map(
  RAW.map(r => [r.code, { ...r, riskBand: bandForScore(r.carbonRiskScore) }]),
);

function bandForScore(s: number): VeritasCountryClimate['riskBand'] {
  if (s < 25) return 'low';
  if (s < 40) return 'moderate';
  if (s < 55) return 'elevated';
  if (s < 70) return 'high';
  return 'critical';
}

/** Return the climate dossier for a country, or null if not in our dataset. */
export function getVeritasCountryClimate(code: string): VeritasCountryClimate | null {
  if (!code) return null;
  return CLIMATE_BY_CODE.get(code.toUpperCase()) ?? null;
}

/** Set of supported ISO codes (for menu enablement). */
export function getSupportedCountryCodes(): string[] {
  return [...CLIMATE_BY_CODE.keys()];
}

/** Format a USD/tCO2e price for display. */
export function formatCarbonPrice(usdPerTon: number): string {
  if (!usdPerTon) return 'No carbon price';
  return `$${usdPerTon.toFixed(usdPerTon >= 10 ? 1 : 2)}/tCO₂e`;
}

/** Get a CSS color token for a risk band. */
export function getRiskBandColor(band: VeritasCountryClimate['riskBand']): string {
  switch (band) {
    case 'low': return '#34d399';      // emerald
    case 'moderate': return '#a3e635'; // lime
    case 'elevated': return '#fbbf24'; // amber
    case 'high': return '#fb923c';     // orange
    case 'critical': return '#f87171'; // red
  }
}
